collections:
  team:
    output: true # each author has their own page

baseurl: /practice1_jekyllFromScratch # essential upon deployment

defaults:
  - scope:
      path: ""
      type: "team" # name of the collection
    values: 
      layout: "member" # name of the html for the particular page
  - scope:
      path: ""
      type: "posts"
    values: 
      layout: "post"
  - scope:
      path: ""
    values: 
      layout: "default"